DISPLAY-929: Added thumbnails for images
os2display/display-api-service pull request #158
Opened 2023-08-04 13:19 UTC by tuj

#### Link to ticket

https://jira.itkdev.dk/browse/DISPLAY-929

#### Description

Added thumbnails for images

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

2023-08-07 21:16 UTC, turegjorup requested changes
Nice to have: Cleanup thumbnail on media delete

2023-08-08 07:37 UTC, tuj commented on composer.json
> +            "@update-api-spec"
Have removed it for now. I generally think tools should make things as easy as possible. What is committed is the developers responsibility.

2023-08-08 07:37 UTC, tuj commented on config/packages/liip_imagine.yaml
> +    driver: "gd"
Added

2023-08-08 08:46 UTC, turegjorup commented on composer.json
> +            "@update-api-spec"
But then we should just remove the API spec check from actions....

Having a check that makes it more difficult to commit something in error, and then updating our tools to make it easier to bypass that check is just stupid.

2023-08-08 08:48 UTC, turegjorup approved these changes

2023-08-08 08:49 UTC, merged