Feature/2829 add feedsource post put delete functionality
os2display/display-api-service pull request #222
Opened 2024-10-28 12:34 UTC by jeppekroghitk

#### Link to ticket

Please add a link to the ticket being addressed by this change.

#### Description

Please include a short description of the suggested change and the reasoning behind the approach you have chosen.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2024-11-13 09:23 UTC, tuj requested changes

2024-11-14 09:11 UTC, jeppekroghitk commented on src/Feed/KobaFeedType.php
> +        $jsonSchema = <<<'JSON'
Primarily aesthetics, but we can do this!

2024-11-18 08:41 UTC, tuj requested changes

2024-11-20 11:31 UTC, tuj approved these changes

2024-11-20 11:38 UTC, merged