Added list screen groups on screen end-point
os2display/display-api-service pull request #32
Opened 2021-10-05 17:16 UTC by cableman

#### Link to ticket

https://jira.itkdev.dk/browse/AR-680

#### Description

List, relate and un-relate screens and screen groups.

#### Screenshot of the result

No yet.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

No comments.

2021-10-05 19:05 UTC, sinejespersen approved these changes

2021-10-06 09:12 UTC, turegjorup requested changes

2021-10-06 10:52 UTC, cableman commented on src/Controller/ScreenGroupsScreensPutController.php
> +        $jsonStr = $this->request->getCurrentRequest()->getContent();
Fixed

2021-10-06 10:58 UTC, cableman commented on src/Controller/ScreenGroupsScreensPutController.php
> +    private function validate(ArrayCollection $data): void
Will do in general PR after merge as it's in the other PR's pattern as well.

2021-10-06 11:02 UTC, cableman commented on src/Controller/ScreenGroupsScreensPutController.php
> +        $content = json_decode($jsonStr);
API platform ensure that it's valid json at this point. So we known it is parseable without errors.

2021-10-06 11:35 UTC, turegjorup approved these changes

2021-10-06 11:47 UTC, merged