AR-692: Change playlist.schedule to an array of Schedule entities
os2display/display-api-service pull request #52
Opened 2021-11-26 08:35 UTC by tuj

#### Link to ticket

https://jira.itkdev.dk/browse/AR-692

#### Description

AR-692: Changed playlist.schedule to playlist.schedules, which is an array of Schedule entities.

#### Screenshot of the result

If your change affects the user interface you should include a screenshot of the result with the pull request.

#### Checklist

- [ ] My code is covered by test cases.
- [ ] My code passes our test (all our tests).
- [ ] My code passes our static analysis suite.
- [ ] My code passes our continuous integration process.

If your code does not pass all the requirements on the checklist you have to add a comment explaining why this change 
should be exempt from the list.

#### Additional comments or questions

If you have any further comments or questions for the reviewer please add them here.

2021-11-26 11:59 UTC, turegjorup commented on src/Entity/Schedule.php
> +    private ?int $duration;
Why allow null values on the object when the db schema doesn't?

2021-11-26 11:59 UTC, turegjorup commented on src/Entity/Schedule.php
> +    private ?RRule $rrule;
Why allow null values on the object when the db schema doesn't?

2021-12-02 09:19 UTC, turegjorup requested changes

2021-12-02 11:48 UTC, tuj commented on src/DataTransformer/PlaylistInputDataTransformer.php
> +        }
I will stick with the for-loop

2021-12-09 11:49 UTC, turegjorup approved these changes

2021-12-09 12:00 UTC, merged